name: pretty_string
description: printer

homepage: https://github.com/Hwan-seok/dart_pretty_print
repository: https://github.com/Hwan-seok/dart_pretty_print
issue_tracker: https://github.com/Hwan-seok/dart_pretty_print/issues


version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  very_good_analysis: ^3.1.0
  test: any
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  equatable: ^2.0.5
  build_runner: ^2.3.3

